debug:
security:
  user:
    password: none
zuul:
  routes:
    organization:
      path: /organization/**
      url: http://localhost:20080/organization
    partner:
      path: /partner/**
      url: http://localhost:30080/partner
    user:
      path: /user/**
      url: http://localhost:9999/auth/user
    auth:
      path: /auth/**
      url: http://localhost:9999/auth

spring:
  server:
    contextPath:
  endpoints:
    restart:
      enabled: true
    shutdown:
      enabled: true
    health:
      sensitive: false
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAddress: true
  ribbon:
    eureka:
      enabled: true
  oauth2:
    sso:
      home:
        secure: false
        path: /,/**/*.html
    client:
      accessTokenUri: http://localhost:9999/auth/oauth/token
      userAuthorizationUri: http://localhost:9999/auth/oauth/authorize
      clientId: loop-gateway
      clientSecret: loop-gateway-secret
    resource:
      jwt:
              keyValue: |
                -----BEGIN PUBLIC KEY-----
                MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
                -----END PUBLIC KEY-----

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: INFO