spring:
server:
  port: 8761
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: true
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
          waitTimeInMsWhenSyncEmpty: 0